### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by UntotaufUrlaub** [tanyuqian/ctc-gen-eval#8]
Hi,
please help me with the following error:

```
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctc_score import SummarizationScorer
>>> scorer = SummarizationScorer(align="D-cnndm", device="cpu")
>>> scorer.score(doc="document", refs=["reference"], hypo="summary", aspect="relevance")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../.local/lib/python3.11/site-packages/ctc_score/summarization_scorer.py", line 18, in score
    return self.score_relevance(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.local/lib/python3.11/site-packages/ctc_score/summarization_scorer.py", line 37, in score_relevance
    aligner_summ_ref = self._get_aligner('summ_to_ref')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.local/lib/python3.11/site-packages/ctc_score/scorer.py", line 55, in _get_aligner
    aligner.load_state_dict(torch.load(ckpt_path, map_location=torch.device(self._device)))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.local/lib/python3.11/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.local/lib/python3.11/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

```

kind regards
P.S. thanks for sharing this metric!

**Comment by tanyuqian** [comment]
Thanks a lot for noticing our work!!

We don't see the error by running your code. Looks your error is from checkpoint loading. Could you try to delete your cache_dir ($HOME/.cache/ctc_score_models) and rerun? Please let us know if it's still not working:)

**Comment by UntotaufUrlaub** [comment]
Thanks for helping me :)

Your suggestion fixed the issue - at least for the cnn model.
When i try to use the xsum model i still encounter an error.
My code is:
 
```
from ctc_score import SummarizationScorer

scorer_xsum = SummarizationScorer(align="D-xsum", device="cuda")
print(scorer_xsum.score(doc="document", refs=["reference"], hypo="summary", aspect="relevance"))
```

The error is:
```
  File "/.../evalctc.py", line 4, in <module>
    print(scorer_xsum.score(doc="document", refs=["reference"], hypo="summary", aspect="relevance"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/lib/python3.11/site-packages/ctc_score/summarization_scorer.py", line 18, in score
    return self.score_relevance(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/lib/python3.11/site-packages/ctc_score/summarization_scorer.py", line 37, in score_relevance
    aligner_summ_ref = self._get_aligner('summ_to_ref')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/lib/python3.11/site-packages/ctc_score/scorer.py", line 36, in _get_aligner
    aligner_link = DR_MODEL_LINKS[self._align][aligner_name]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'summ_to_ref'
```
(I also tried on cpu, think it was the same error)
Could you please help me with this, too?

**Comment by tanyuqian** [comment]
Thanks for the follow-up! 

The ```xsum``` scorers don't support ```aspect='relevance'``` for now, because there is nowhere to verify its performance (see Fig.3 and Fig.4 in [our paper](https://arxiv.org/pdf/2109.06379.pdf)). Sorry for not declaring this in README.

**Comment by UntotaufUrlaub** [comment]
I see. Thank you!
